import { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { uploadProductImage, uploadSiteImage } from '../imagekit';

const statuses=['Pedido recebido','Aguardando confirmação','Em separação','Saiu para entrega','Concluído','Cancelado'];
const SITE_SETTINGS_ID='qfl-site-settings';
const siteDefaults={logoUrl:'',heroEyebrow:'QUITANDA FEIRA LIVRE',heroTitleBefore:'O melhor da',heroTitleHighlight:'feira',heroTitleAfter:'para sua casa.',heroDescription:'Frutas, verduras e legumes fresquinhos em Santa Maria da Vitória.',storeTag:'NOSSA LOJA',storeTitle:'Santa Maria da Vitória/BA',storeAddress:'Endereço da Quitanda Feira Livre — edite no painel administrativo.',storePhone:'(77) 99999-9999',catalogTag:'CATÁLOGO',catalogTitle:'Produtos disponíveis',catalogDescription:'Confira os produtos disponíveis na Quitanda Feira Livre.'};

export default function Admin(){
 const [tab,setTab]=useState('orders');
 const [orders,setOrders]=useState([]);
 const [products,setProducts]=useState([]);
 const [editing,setEditing]=useState(null);
 const [form,setForm]=useState({name:'',category:'',price:'',unit:'un',stock:'',available:true,imageUrl:''});
 const [file,setFile]=useState(null);
 const [busy,setBusy]=useState(false);
 const [orderSearch,setOrderSearch]=useState('');
 const [siteForm,setSiteForm]=useState(siteDefaults);
 const [siteFile,setSiteFile]=useState(null);
 const [siteBusy,setSiteBusy]=useState(false);
 const [siteMsg,setSiteMsg]=useState('');

 useEffect(()=>{const q=query(collection(db,'orders'),orderBy('createdAt','desc'));return onSnapshot(q,s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()}))))},[]);
 useEffect(()=>onSnapshot(collection(db,'products'),s=>setProducts(s.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.id!==SITE_SETTINGS_ID&&!p.isSiteSettings))),[]);
 useEffect(()=>onSnapshot(doc(db,'products',SITE_SETTINGS_ID),s=>setSiteForm({...siteDefaults,...(s.exists()?s.data():{})})),[]);

 const saveProduct=async e=>{e.preventDefault();setBusy(true);try{let imageUrl=form.imageUrl||'';if(file){imageUrl=await uploadProductImage(file)}const payload={...form,price:Number(form.price),stock:Number(form.stock||0),imageUrl,updatedAt:serverTimestamp()};if(editing)await updateDoc(doc(db,'products',editing),payload);else await addDoc(collection(db,'products'),{...payload,createdAt:serverTimestamp()});setForm({name:'',category:'',price:'',unit:'un',stock:'',available:true,imageUrl:''});setFile(null);setEditing(null)}finally{setBusy(false)}};
 const edit=p=>{setEditing(p.id);setForm({name:p.name||'',category:p.category||'',price:p.price||'',unit:p.unit||'un',stock:p.stock??'',available:!!p.available,imageUrl:p.imageUrl||''});setTab('products')};

 const updateStatus=async(o,status)=>{await updateDoc(doc(db,'orders',o.id),{status,archived:status==='Concluído',updatedAt:serverTimestamp(),...(status==='Concluído'?{archivedAt:serverTimestamp()}:{})})};
 const archiveOrder=async(o)=>updateDoc(doc(db,'orders',o.id),{archived:true,archivedAt:serverTimestamp(),updatedAt:serverTimestamp()});
 const restoreOrder=async(o)=>updateDoc(doc(db,'orders',o.id),{archived:false,updatedAt:serverTimestamp()});

 const normalizedSearch=orderSearch.trim().toUpperCase();
 const currentOrders=useMemo(()=>orders.filter(o=>!o.archived && (!normalizedSearch || String(o.code||'').toUpperCase().includes(normalizedSearch))),[orders,normalizedSearch]);
 const archivedOrders=useMemo(()=>orders.filter(o=>o.archived && (!normalizedSearch || String(o.code||'').toUpperCase().includes(normalizedSearch))),[orders,normalizedSearch]);

 const saveSite=async e=>{e.preventDefault();setSiteBusy(true);setSiteMsg('');try{let logoUrl=siteForm.logoUrl||'';if(siteFile)logoUrl=await uploadSiteImage(siteFile);await setDoc(doc(db,'products',SITE_SETTINGS_ID),{...siteForm,logoUrl,available:false,isSiteSettings:true,updatedAt:serverTimestamp()},{merge:true});setSiteFile(null);setSiteMsg('Alterações do site salvas com sucesso.')}catch(err){setSiteMsg(err.message||'Não foi possível salvar as alterações.')}finally{setSiteBusy(false)}};

 const OrdersTable=({items,archived=false})=><div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Telefone</th><th>Valor</th><th>Pagamento</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map(o=><tr key={o.id}><td><b>{o.code}</b><small>{o.address}</small></td><td>{o.customerName}</td><td>{o.phone}</td><td>R$ {Number(o.total).toFixed(2).replace('.',',')}</td><td>{o.paymentMethod}</td><td><select value={o.status} onChange={e=>updateStatus(o,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td>{archived?<button className="mini-btn" onClick={()=>restoreOrder(o)}>Restaurar</button>:<button className="mini-btn" onClick={()=>archiveOrder(o)}>Arquivar</button>}</td></tr>)}{!items.length&&<tr><td colSpan="7"><div className="empty">Nenhum pedido encontrado.</div></td></tr>}</tbody></table></div>;

 return <main className="admin-layout"><aside className="admin-side"><h2>Quitanda<br/>Feira Livre</h2><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Pedidos atuais</button><button className={tab==='archived'?'active':''} onClick={()=>setTab('archived')}>Pedidos arquivados</button><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>Produtos e estoque</button><button className={tab==='site'?'active':''} onClick={()=>setTab('site')}>Editar site</button></aside><section className="admin-content">

 {tab==='orders'&&<><span className="tag red">ADMINISTRATIVO</span><h1>Pedidos por ordem de chegada</h1><div className="admin-search"><label>Buscar pelo número do pedido<input placeholder="Ex.: QFL-2026-1234" value={orderSearch} onChange={e=>setOrderSearch(e.target.value)}/></label></div><OrdersTable items={currentOrders}/></>}
 {tab==='archived'&&<><span className="tag blue">ARQUIVO</span><h1>Pedidos arquivados</h1><div className="admin-search"><label>Buscar pelo número do pedido<input placeholder="Ex.: QFL-2026-1234" value={orderSearch} onChange={e=>setOrderSearch(e.target.value)}/></label></div><OrdersTable items={archivedOrders} archived/></>}
 {tab==='products'&&<><span className="tag green">CATÁLOGO</span><h1>{editing?'Editar produto':'Novo produto'}</h1><form className="product-form" onSubmit={saveProduct}><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Categoria<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Preço<input required type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Unidade<select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option value="un">un</option><option value="kg">kg</option><option value="maço">maço</option><option value="bandeja">bandeja</option></select></label><label>Estoque<input type="number" min="0" step="0.01" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label>Imagem<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="check"><input type="checkbox" checked={form.available} onChange={e=>setForm({...form,available:e.target.checked})}/> Produto disponível</label><button className="btn green" disabled={busy}>{busy?'Salvando...':'Salvar produto'}</button>{editing&&<button type="button" className="ghost" onClick={()=>{setEditing(null);setForm({name:'',category:'',price:'',unit:'un',stock:'',available:true,imageUrl:''})}}>Cancelar</button>}</form><div className="table-wrap"><table><thead><tr><th>Produto</th><th>Preço</th><th>Estoque</th><th>Disponibilidade</th><th>Ações</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><div className="mini-product">{p.imageUrl?<img src={p.imageUrl}/>:<span>🥦</span>}<b>{p.name}</b></div></td><td>R$ {Number(p.price).toFixed(2).replace('.',',')} / {p.unit}</td><td>{Number(p.stock||0)} {p.unit}</td><td><span className={p.available?'pill ok':'pill no'}>{p.available?'Disponível':'Indisponível'}</span></td><td><button className="mini-btn" onClick={()=>edit(p)}>Editar</button> <button className="mini-btn danger" onClick={()=>deleteDoc(doc(db,'products',p.id))}>Excluir</button></td></tr>)}</tbody></table></div></>}
 {tab==='site'&&<><span className="tag blue">CONTEÚDO</span><h1>Editar textos e imagens do site</h1><p className="admin-help">As alterações feitas aqui aparecem para os clientes na página inicial e no cabeçalho.</p><form className="site-form" onSubmit={saveSite}><div className="site-form-card"><h2>Logo da Quitanda</h2>{siteForm.logoUrl&&<img className="admin-logo-preview" src={siteForm.logoUrl} alt="Logo atual"/>}<label>Trocar logo<input type="file" accept="image/*" onChange={e=>setSiteFile(e.target.files?.[0]||null)}/></label></div><div className="site-form-card"><h2>Destaque inicial</h2><label>Texto superior<input value={siteForm.heroEyebrow} onChange={e=>setSiteForm({...siteForm,heroEyebrow:e.target.value})}/></label><div className="form-three"><label>Início do título<input value={siteForm.heroTitleBefore} onChange={e=>setSiteForm({...siteForm,heroTitleBefore:e.target.value})}/></label><label>Palavra destacada<input value={siteForm.heroTitleHighlight} onChange={e=>setSiteForm({...siteForm,heroTitleHighlight:e.target.value})}/></label><label>Final do título<input value={siteForm.heroTitleAfter} onChange={e=>setSiteForm({...siteForm,heroTitleAfter:e.target.value})}/></label></div><label>Descrição<textarea value={siteForm.heroDescription} onChange={e=>setSiteForm({...siteForm,heroDescription:e.target.value})}/></label></div><div className="site-form-card"><h2>Nossa loja</h2><label>Etiqueta<input value={siteForm.storeTag} onChange={e=>setSiteForm({...siteForm,storeTag:e.target.value})}/></label><label>Título<input value={siteForm.storeTitle} onChange={e=>setSiteForm({...siteForm,storeTitle:e.target.value})}/></label><label>Endereço<input value={siteForm.storeAddress} onChange={e=>setSiteForm({...siteForm,storeAddress:e.target.value})}/></label><label>Telefone<input value={siteForm.storePhone} onChange={e=>setSiteForm({...siteForm,storePhone:e.target.value})}/></label></div><div className="site-form-card"><h2>Catálogo</h2><label>Etiqueta<input value={siteForm.catalogTag} onChange={e=>setSiteForm({...siteForm,catalogTag:e.target.value})}/></label><label>Título<input value={siteForm.catalogTitle} onChange={e=>setSiteForm({...siteForm,catalogTitle:e.target.value})}/></label><label>Descrição<input value={siteForm.catalogDescription} onChange={e=>setSiteForm({...siteForm,catalogDescription:e.target.value})}/></label></div>{siteMsg&&<div className="info-box">{siteMsg}</div>}<button className="btn blue" disabled={siteBusy}>{siteBusy?'Salvando...':'Salvar alterações do site'}</button></form></>}
 </section></main>
}
