import { useContext, useMemo, useState } from 'react';
import { doc, serverTimestamp, setDoc } from 'firebase/firestore';
import { useNavigate } from 'react-router-dom';
import { AppContext } from '../App';
import { db } from '../firebase';

const makeCode=()=>`QFL-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
export default function Cart(){const {cart,setCart,user,profile}=useContext(AppContext);const nav=useNavigate();const [form,setForm]=useState({address:'',reference:'',paymentMethod:'Dinheiro na entrega',notes:''});const [msg,setMsg]=useState('');const total=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.qty,0),[cart]);
 const changeQty=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:Math.max(1,i.qty+d)}:i)); const remove=id=>setCart(c=>c.filter(i=>i.id!==id));
 const checkout=async()=>{if(!user){nav('/login');return} if(!cart.length){setMsg('Seu carrinho está vazio.');return} if(!form.address.trim()){setMsg('Informe o endereço de entrega.');return} const code=makeCode(); const order={code,userId:user.uid,customerName:profile?.name||'',phone:profile?.phone||'',address:form.address.trim(),reference:form.reference.trim(),paymentMethod:form.paymentMethod,notes:form.notes.trim(),items:cart,total,status:'Pedido recebido',createdAt:serverTimestamp(),updatedAt:serverTimestamp()}; await setDoc(doc(db,'orders',code),order); setCart([]); nav(`/acompanhar?pedido=${code}`)};
 return <main className="section"><div className="section-head"><div><span className="tag red">CARRINHO</span><h1>Finalize seu pedido</h1></div></div>{msg&&<div className="alert">{msg}</div>}<div className="checkout-grid"><section className="panel"><h2>Produtos</h2>{cart.map(i=><div className="cart-row" key={i.id}><div>{i.imageUrl?<img src={i.imageUrl}/>:<span>🍎</span>}<b>{i.name}</b></div><div className="qty"><button onClick={()=>changeQty(i.id,-1)}>-</button><span>{i.qty}</span><button onClick={()=>changeQty(i.id,1)}>+</button></div><strong>R$ {(i.price*i.qty).toFixed(2).replace('.',',')}</strong><button className="link-danger" onClick={()=>remove(i.id)}>Remover</button></div>)}<div className="total">Total: <b>R$ {total.toFixed(2).replace('.',',')}</b></div></section><section className="panel"><h2>Entrega e pagamento</h2><label>Endereço completo<textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Ponto de referência<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label>Pagamento<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}><option>Dinheiro na entrega</option><option>PIX na entrega</option><option>Cartão na entrega</option></select></label><div className="info-box">Nenhum pagamento é feito agora no site. O pagamento será realizado no momento da entrega.</div><label>Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="btn red full" onClick={checkout}>Enviar pedido</button></section></div></main>}
